// Om Parkash Namkeens — product catalogue (editable source of truth).
// The page also inlines this data as window.__CATALOGUE.
export const CATEGORIES = [
  {
    "id": "sev-and-bhujia",
    "name": "Sev & Bhujia",
    "order": 1,
    "expectedCount": 8,
    "count": 8,
    "connected": 8
  },
  {
    "id": "signature-mixtures",
    "name": "Signature Mixtures",
    "order": 2,
    "expectedCount": 14,
    "count": 14,
    "connected": 14
  },
  {
    "id": "traditional-crunchies",
    "name": "Traditional Crunchies",
    "order": 3,
    "expectedCount": 10,
    "count": 10,
    "connected": 10
  },
  {
    "id": "dal-peas-and-roasted-snacks",
    "name": "Dal, Peas & Roasted Snacks",
    "order": 4,
    "expectedCount": 9,
    "count": 9,
    "connected": 9
  },
  {
    "id": "boondi",
    "name": "Boondi",
    "order": 5,
    "expectedCount": 2,
    "count": 2,
    "connected": 2
  },
  {
    "id": "chips",
    "name": "Chips",
    "order": 6,
    "expectedCount": 2,
    "count": 2,
    "connected": 2
  }
];

export const PRODUCTS = [
  {
    "id": "aaloo-bhujia",
    "slug": "aaloo-bhujia",
    "name": "Aloo Bhujia",
    "category": "Sev & Bhujia",
    "imageFilename": "aaloo-bhujia.webp",
    "image": "assets/products/aaloo-bhujia.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "ajwain-sev",
    "slug": "ajwain-sev",
    "name": "Ajwain Sev",
    "category": "Sev & Bhujia",
    "imageFilename": "ajwain-sev.webp",
    "image": "assets/products/ajwain-sev.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "bhalla",
    "slug": "bhalla",
    "name": "Bhalla",
    "category": "Traditional Crunchies",
    "imageFilename": "bhalla.webp",
    "image": "assets/products/bhalla.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "bhojpuri-mix",
    "slug": "bhojpuri-mix",
    "name": "Bhojpuri Mix",
    "category": "Signature Mixtures",
    "imageFilename": "bhojpuri-mix.webp",
    "image": "assets/products/bhojpuri-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "bikaneri-bhujia",
    "slug": "bikaneri-bhujia",
    "name": "Bikaneri Bhujia",
    "category": "Sev & Bhujia",
    "imageFilename": "bikaneri-bhujia.webp",
    "image": "assets/products/bikaneri-bhujia.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "bombay-mix",
    "slug": "bombay-mix",
    "name": "Bombay Mix",
    "category": "Signature Mixtures",
    "imageFilename": "bombay-mix.webp",
    "image": "assets/products/bombay-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "chameli-mix",
    "slug": "chameli-mix",
    "name": "Chameli Mix",
    "category": "Signature Mixtures",
    "imageFilename": "chameli-mix.webp",
    "image": "assets/products/chameli-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "chana-jor",
    "slug": "chana-jor",
    "name": "Chana Jor",
    "category": "Dal, Peas & Roasted Snacks",
    "imageFilename": "chana-jor.webp",
    "image": "assets/products/chana-jor.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "disco-mix",
    "slug": "disco-mix",
    "name": "Disco Mix",
    "category": "Signature Mixtures",
    "imageFilename": "disco-mix.webp",
    "image": "assets/products/disco-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "fafda-mix",
    "slug": "fafda-mix",
    "name": "Fafda Mix",
    "category": "Signature Mixtures",
    "imageFilename": "fafda-mix.webp",
    "image": "assets/products/fafda-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "fafda",
    "slug": "fafda",
    "name": "Fafda",
    "category": "Traditional Crunchies",
    "imageFilename": "fafda.webp",
    "image": "assets/products/fafda.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "gathia-mix",
    "slug": "gathia-mix",
    "name": "Gathia Mix",
    "category": "Signature Mixtures",
    "imageFilename": "gathia-mix.webp",
    "image": "assets/products/gathia-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "gathia",
    "slug": "gathia",
    "name": "Gathia",
    "category": "Traditional Crunchies",
    "imageFilename": "gathia.webp",
    "image": "assets/products/gathia.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "green-moong-dal",
    "slug": "green-moong-dal",
    "name": "Green Moong Dal",
    "category": "Dal, Peas & Roasted Snacks",
    "imageFilename": "green-moong-dal.webp",
    "image": "assets/products/green-moong-dal.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "green-pea",
    "slug": "green-pea",
    "name": "Green Pea",
    "category": "Dal, Peas & Roasted Snacks",
    "imageFilename": "green-pea.webp",
    "image": "assets/products/green-pea.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "kaju",
    "slug": "kaju",
    "name": "Kaju",
    "category": "Traditional Crunchies",
    "imageFilename": "kaju.webp",
    "image": "assets/products/kaju.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "khatha-meetha-bhujia",
    "slug": "khatha-meetha-bhujia",
    "name": "Khatta Meetha Bhujia",
    "category": "Signature Mixtures",
    "imageFilename": "khatha-meetha-bhujia.webp",
    "image": "assets/products/khatha-meetha-bhujia.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "kofta",
    "slug": "kofta",
    "name": "Kofta",
    "category": "Traditional Crunchies",
    "imageFilename": "kofta.webp",
    "image": "assets/products/kofta.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "laccha-mix",
    "slug": "laccha-mix",
    "name": "Laccha Mix",
    "category": "Signature Mixtures",
    "imageFilename": "laccha-mix.webp",
    "image": "assets/products/laccha-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "laccha",
    "slug": "laccha",
    "name": "Laccha",
    "category": "Traditional Crunchies",
    "imageFilename": "laccha.webp",
    "image": "assets/products/laccha.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "lasan-sev",
    "slug": "lasan-sev",
    "name": "Lasan Sev",
    "category": "Sev & Bhujia",
    "imageFilename": "lasan-sev.webp",
    "image": "assets/products/lasan-sev.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "light-mix",
    "slug": "light-mix",
    "name": "Light Mix",
    "category": "Signature Mixtures",
    "imageFilename": "light-mix.webp",
    "image": "assets/products/light-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "lite-mix",
    "slug": "lite-mix",
    "name": "Lite Mix",
    "category": "Signature Mixtures",
    "imageFilename": "lite-mix.webp",
    "image": "assets/products/lite-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "malai-bhujia",
    "slug": "malai-bhujia",
    "name": "Malai Bhujia",
    "category": "Sev & Bhujia",
    "imageFilename": "malai-bhujia.webp",
    "image": "assets/products/malai-bhujia.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "masala-channa",
    "slug": "masala-channa",
    "name": "Masala Channa",
    "category": "Dal, Peas & Roasted Snacks",
    "imageFilename": "masala-channa.webp",
    "image": "assets/products/masala-channa.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "masala-chips",
    "slug": "masala-chips",
    "name": "Masala Chips",
    "category": "Chips",
    "imageFilename": "masala-chips.webp",
    "image": "assets/products/masala-chips.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "masala-pakooda",
    "slug": "masala-pakooda",
    "name": "Masala Pakooda",
    "category": "Traditional Crunchies",
    "imageFilename": "masala-pakooda.webp",
    "image": "assets/products/masala-pakooda.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "methi-sev",
    "slug": "methi-sev",
    "name": "Methi Sev",
    "category": "Sev & Bhujia",
    "imageFilename": "methi-sev.webp",
    "image": "assets/products/methi-sev.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "millet-mix",
    "slug": "millet-mix",
    "name": "Millet Mix",
    "category": "Dal, Peas & Roasted Snacks",
    "imageFilename": "millet-mix.webp",
    "image": "assets/products/millet-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "moong-dal",
    "slug": "moong-dal",
    "name": "Moong Dal",
    "category": "Dal, Peas & Roasted Snacks",
    "imageFilename": "moong-dal.webp",
    "image": "assets/products/moong-dal.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "moong-jor",
    "slug": "moong-jor",
    "name": "Moong Jor",
    "category": "Dal, Peas & Roasted Snacks",
    "imageFilename": "moong-jor.webp",
    "image": "assets/products/moong-jor.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "mota-mix",
    "slug": "mota-mix",
    "name": "Mota Mix",
    "category": "Signature Mixtures",
    "imageFilename": "mota-mix.webp",
    "image": "assets/products/mota-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "nav-rattan",
    "slug": "nav-rattan",
    "name": "Nav Rattan",
    "category": "Signature Mixtures",
    "imageFilename": "nav-rattan.webp",
    "image": "assets/products/nav-rattan.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "panch-rattan",
    "slug": "panch-rattan",
    "name": "Panch Rattan",
    "category": "Signature Mixtures",
    "imageFilename": "panch-rattan.webp",
    "image": "assets/products/panch-rattan.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "paneer-bhujia",
    "slug": "paneer-bhujia",
    "name": "Paneer Bhujia",
    "category": "Sev & Bhujia",
    "imageFilename": "paneer-bhujia.webp",
    "image": "assets/products/paneer-bhujia.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "plain-boondi",
    "slug": "plain-boondi",
    "name": "Plain Boondi",
    "category": "Boondi",
    "imageFilename": "plain-boondi.webp",
    "image": "assets/products/plain-boondi.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "plain-pakooda",
    "slug": "plain-pakooda",
    "name": "Plain Pakooda",
    "category": "Traditional Crunchies",
    "imageFilename": "plain-pakooda.webp",
    "image": "assets/products/plain-pakooda.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "pudina-boondi",
    "slug": "pudina-boondi",
    "name": "Pudina Boondi",
    "category": "Boondi",
    "imageFilename": "pudina-boondi.webp",
    "image": "assets/products/pudina-boondi.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "salted-chips",
    "slug": "salted-chips",
    "name": "Salted Chips",
    "category": "Chips",
    "imageFilename": "salted-chips.webp",
    "image": "assets/products/salted-chips.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "sing-dana",
    "slug": "sing-dana",
    "name": "Sing Dana",
    "category": "Dal, Peas & Roasted Snacks",
    "imageFilename": "sing-dana.webp",
    "image": "assets/products/sing-dana.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "soyabean-mix",
    "slug": "soyabean-mix",
    "name": "Soyabean Mix",
    "category": "Dal, Peas & Roasted Snacks",
    "imageFilename": "soyabean-mix.webp",
    "image": "assets/products/soyabean-mix.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "tasty-crunchy-munchy",
    "slug": "tasty-crunchy-munchy",
    "name": "Tasty Crunchy Munchy",
    "category": "Traditional Crunchies",
    "imageFilename": "tasty-crunchy-munchy.webp",
    "image": "assets/products/tasty-crunchy-munchy.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "tiranga",
    "slug": "tiranga",
    "name": "Tiranga",
    "category": "Signature Mixtures",
    "imageFilename": "tiranga.webp",
    "image": "assets/products/tiranga.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "zeera-sev",
    "slug": "zeera-sev",
    "name": "Zeera Sev",
    "category": "Sev & Bhujia",
    "imageFilename": "zeera-sev.webp",
    "image": "assets/products/zeera-sev.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  },
  {
    "id": "masala-kaju",
    "slug": "masala-kaju",
    "name": "Masala Kaju",
    "category": "Traditional Crunchies",
    "imageFilename": "masala-kaju.webp",
    "image": "assets/products/masala-kaju.webp",
    "imageConnected": true,
    "price": null,
    "packSizes": [],
    "stockStatus": "pending-confirmation",
    "featured": false,
    "bestseller": false,
    "ingredients": null,
    "allergens": null,
    "shelfLife": "Shelf-life details pending product-level confirmation"
  }
];

export const productsByCategory = (name) => PRODUCTS.filter(p => p.category === name);
export const categoryCount = (name) => PRODUCTS.filter(p => p.category === name).length;
export const findProduct = (slug) => PRODUCTS.find(p => p.slug === slug);
export const WHATSAPP = '+91 93568 50599';
